apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    project: roboshop
    component: mysql
    tier: backend
    environment: dev
  annotations:
    description: "This pod is created to demonstrat pod annotations"
    jenkins: "https://jenkins.com/build/job/roboshop-catalogue/3.0"
spec:
  containers:
  - name: nginx
    image: nginx
    